//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greencard.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.SubCategories = new HashSet<SubCategory>();
        }
    
        public int ID { get; set; }
        public int TopCategoryID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Count { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Status { get; set; }
        public string Slug { get; set; }
    
        public virtual TopCategory TopCategory { get; set; }
        public virtual ICollection<SubCategory> SubCategories { get; set; }
    }
}
