//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greencard.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreenUserDetail
    {
        public int ID { get; set; }
        public Nullable<int> GreenUserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> BirthCity { get; set; }
        public Nullable<int> CountryBorn { get; set; }
        public Nullable<int> CountryEligibility { get; set; }
        public string Image { get; set; }
        public string InCareOf { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AdressCityTown { get; set; }
        public string AdressDistrictCountyProvinceState { get; set; }
        public string AdressPostalCode { get; set; }
        public Nullable<int> AdressCountry { get; set; }
        public Nullable<int> CountryLiveToday { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public Nullable<int> Education { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> NumberofChildren { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
