//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greencard.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreenOrderDetail
    {
        public int ID { get; set; }
        public Nullable<int> GreenOrderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Status { get; set; }
    
        public virtual GreenOrder GreenOrder { get; set; }
        public virtual GreenProduct GreenProduct { get; set; }
    }
}
