//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greencard.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreenCategory
    {
        public GreenCategory()
        {
            this.GreenProducts = new HashSet<GreenProduct>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ICollection<GreenProduct> GreenProducts { get; set; }
    }
}
