//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greencard.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreenUser
    {
        public GreenUser()
        {
            this.GreenOrders = new HashSet<GreenOrder>();
            this.GreenUserDetails = new HashSet<GreenUserDetail>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int BeginYear { get; set; }
        public Nullable<int> EndYear { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<GreenOrder> GreenOrders { get; set; }
        public virtual ICollection<GreenUserDetail> GreenUserDetails { get; set; }
    }
}
