//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greencard.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreenOrder
    {
        public GreenOrder()
        {
            this.GreenOrderDetails = new HashSet<GreenOrderDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> GreenUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Status { get; set; }
    
        public virtual GreenUser GreenUser { get; set; }
        public virtual ICollection<GreenOrderDetail> GreenOrderDetails { get; set; }
    }
}
