//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greencard.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreenProduct
    {
        public GreenProduct()
        {
            this.GreenOrderDetails = new HashSet<GreenOrderDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> GreenCategoryId { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual GreenCategory GreenCategory { get; set; }
        public virtual ICollection<GreenOrderDetail> GreenOrderDetails { get; set; }
    }
}
