//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greencard.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductDetails = new HashSet<ProductDetail>();
            this.ProductImages = new HashSet<ProductImage>();
        }
    
        public int ID { get; set; }
        public int ProductCategoryID { get; set; }
        public string Title { get; set; }
        public Nullable<float> Price { get; set; }
        public string Location { get; set; }
        public string MainImage { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Status { get; set; }
        public string Slug { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ICollection<ProductDetail> ProductDetails { get; set; }
        public virtual ICollection<ProductImage> ProductImages { get; set; }
    }
}
